name: breez_sdk_spark
publish_to: none

environment:
  sdk: '>=3.7.0 <4.0.0'

resolution: workspace

dependencies:
  breez_sdk_spark_flutter:
    path: /home/islabtc/AndroidStudioProjects/breezmisty/spark-sdk/packages/flutter
  logging: ^1.3.0
